# -*- coding: utf-8 -*-
"""bandnamegenerator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e-895pDiHH-QH6Te_iCwo-z1Lfl1bqe9
"""

print("Welcome to the band name generator.\n")
city=input("What's name of the city you grew up in?\n")
pet=input("What's your pet's name?\n")
print("Your band name is "+ city +" "+ pet)